import 'package:lingola_travel/generated/locale_keys.g.dart';

class LanguageDataManager {
  LanguageDataManager._(); // Nesne üretilmesini engelle (Sadece static kullanılacak)

  // ===========================================================================
  // KATEGORİLERE GÖRE KELİMELER (VOCABULARY)
  // ===========================================================================
  static const Map<String, List<String>> vocabularyData = {
    LocaleKeys.home_catGeneral: _generalVocabulary,
    LocaleKeys.home_catTravel: _travelVocabulary,
    LocaleKeys.home_catAccommodation: _accommodationVocabulary,
    LocaleKeys.home_catFoodAndDrink: _foodAndDrinkVocabulary,
    LocaleKeys.home_catCulture: _sightseeingVocabulary,
    LocaleKeys.home_catShop: _shoppingVocabulary,
    LocaleKeys.home_catDirection: _directionsVocabulary,
    LocaleKeys.home_catSport: _sportsVocabulary,
    LocaleKeys.home_catHealth: _healthVocabulary,
    LocaleKeys.home_catBusiness: _businessVocabulary,
    LocaleKeys.home_catEmergency: _emergencyVocabulary,
  };

  // ===========================================================================
  // KATEGORİLERE GÖRE CÜMLELER (SENTENCES)
  // ===========================================================================
  static const Map<String, List<String>> sentencesData = {
    LocaleKeys.home_catGeneral: _generalSentences,
    LocaleKeys.home_catTravel: _travelSentences,
    LocaleKeys.home_catAccommodation: _accommodationSentences,
    LocaleKeys.home_catFoodAndDrink: _foodAndDrinkSentences,
    LocaleKeys.home_catCulture: _sightseeingSentences,
    LocaleKeys.home_catShop: _shoppingSentences,
    LocaleKeys.home_catDirection: _directionsSentences,
    LocaleKeys.home_catSport: _sportsSentences,
    LocaleKeys.home_catHealth: _healthSentences,
    LocaleKeys.home_catBusiness: _businessSentences,
    LocaleKeys.home_catEmergency: _emergencySentences,
  };

  // ===========================================================================
  // 1. GENERAL
  // ===========================================================================
  static const List<String> _generalVocabulary = [
    LocaleKeys.vocabulary_general_hello,
    LocaleKeys.vocabulary_general_hi,
    LocaleKeys.vocabulary_general_please,
    LocaleKeys.vocabulary_general_thanks,
    LocaleKeys.vocabulary_general_youreWelcome,
    LocaleKeys.vocabulary_general_sorry,
    LocaleKeys.vocabulary_general_yes,
    LocaleKeys.vocabulary_general_no,
    LocaleKeys.vocabulary_general_okay,
    LocaleKeys.vocabulary_general_alright,
    LocaleKeys.vocabulary_general_iUnderstand,
    LocaleKeys.vocabulary_general_iDontUnderstand,
    LocaleKeys.vocabulary_general_again,
    LocaleKeys.vocabulary_general_slow,
    LocaleKeys.vocabulary_general_fast,
    LocaleKeys.vocabulary_general_wait,
    LocaleKeys.vocabulary_general_now,
    LocaleKeys.vocabulary_general_later,
    LocaleKeys.vocabulary_general_today,
    LocaleKeys.vocabulary_general_tomorrow,
    LocaleKeys.vocabulary_general_yesterday,
    LocaleKeys.vocabulary_general_here,
    LocaleKeys.vocabulary_general_there,
    LocaleKeys.vocabulary_general_where,
    LocaleKeys.vocabulary_general_what,
    LocaleKeys.vocabulary_general_why,
    LocaleKeys.vocabulary_general_how,
    LocaleKeys.vocabulary_general_who,
    LocaleKeys.vocabulary_general_which,
    LocaleKeys.vocabulary_general_language,
    LocaleKeys.vocabulary_general_english,
    LocaleKeys.vocabulary_general_turkish,
    LocaleKeys.vocabulary_general_help,
    LocaleKeys.vocabulary_general_problem,
    LocaleKeys.vocabulary_general_necessary,
    LocaleKeys.vocabulary_general_possible,
    LocaleKeys.vocabulary_general_urgent,
    LocaleKeys.vocabulary_general_important,
    LocaleKeys.vocabulary_general_correct,
    LocaleKeys.vocabulary_general_wrong,
    LocaleKeys.vocabulary_general_good,
    LocaleKeys.vocabulary_general_bad,
    LocaleKeys.vocabulary_general_nice,
    LocaleKeys.vocabulary_general_difficult,
    LocaleKeys.vocabulary_general_easy,
    LocaleKeys.vocabulary_general_thankYou,
    LocaleKeys.vocabulary_general_noProblem,
    LocaleKeys.vocabulary_general_excuseMe,
    LocaleKeys.vocabulary_general_oneMoment,
  ];

  static const List<String> _generalSentences = [
    LocaleKeys.sentences_general_hello,
    LocaleKeys.sentences_general_goodDay,
    LocaleKeys.sentences_general_thankYou,
    LocaleKeys.sentences_general_youreWelcome,
    LocaleKeys.sentences_general_canYouHelpMe,
    LocaleKeys.sentences_general_iDontUnderstand,
    LocaleKeys.sentences_general_canYouSpeakMoreSlowly,
    LocaleKeys.sentences_general_canYouRepeatThat,
    LocaleKeys.sentences_general_iDontUnderstandThis,
    LocaleKeys.sentences_general_iDontSpeakTurkish,
    LocaleKeys.sentences_general_doYouSpeakEnglish,
    LocaleKeys.sentences_general_whatDoesThisMean,
    LocaleKeys.sentences_general_oneMomentPlease,
    LocaleKeys.sentences_general_noProblem,
    LocaleKeys.sentences_general_imSorry,
  ];

  // ===========================================================================
  // 2. TRAVEL
  // ===========================================================================
  static const List<String> _travelVocabulary = [
    LocaleKeys.vocabulary_travel_ticket,
    LocaleKeys.vocabulary_travel_reservation,
    LocaleKeys.vocabulary_travel_station,
    LocaleKeys.vocabulary_travel_airport,
    LocaleKeys.vocabulary_travel_terminal,
    LocaleKeys.vocabulary_travel_platform,
    LocaleKeys.vocabulary_travel_gate,
    LocaleKeys.vocabulary_travel_departure,
    LocaleKeys.vocabulary_travel_arrival,
    LocaleKeys.vocabulary_travel_leave,
    LocaleKeys.vocabulary_travel_service,
    LocaleKeys.vocabulary_travel_time,
    LocaleKeys.vocabulary_travel_delay,
    LocaleKeys.vocabulary_travel_cancellation,
    LocaleKeys.vocabulary_travel_transfer,
    LocaleKeys.vocabulary_travel_line,
    LocaleKeys.vocabulary_travel_direction,
    LocaleKeys.vocabulary_travel_stop,
    LocaleKeys.vocabulary_travel_route,
    LocaleKeys.vocabulary_travel_train,
    LocaleKeys.vocabulary_travel_bus,
    LocaleKeys.vocabulary_travel_metro,
    LocaleKeys.vocabulary_travel_tram,
    LocaleKeys.vocabulary_travel_taxi,
    LocaleKeys.vocabulary_travel_plane,
    LocaleKeys.vocabulary_travel_flight,
    LocaleKeys.vocabulary_travel_seat,
    LocaleKeys.vocabulary_travel_empty,
    LocaleKeys.vocabulary_travel_full,
    LocaleKeys.vocabulary_travel_luggage,
    LocaleKeys.vocabulary_travel_suitcase,
    LocaleKeys.vocabulary_travel_carryOn,
    LocaleKeys.vocabulary_travel_passport,
    LocaleKeys.vocabulary_travel_id,
    LocaleKeys.vocabulary_travel_boarding,
    LocaleKeys.vocabulary_travel_control,
    LocaleKeys.vocabulary_travel_security,
    LocaleKeys.vocabulary_travel_checkIn,
    LocaleKeys.vocabulary_travel_boardingPass,
    LocaleKeys.vocabulary_travel_map,
    LocaleKeys.vocabulary_travel_address,
    LocaleKeys.vocabulary_travel_road,
    LocaleKeys.vocabulary_travel_traffic,
    LocaleKeys.vocabulary_travel_speed,
    LocaleKeys.vocabulary_travel_distance,
    LocaleKeys.vocabulary_travel_near,
    LocaleKeys.vocabulary_travel_far,
    LocaleKeys.vocabulary_travel_ticketOffice,
    LocaleKeys.vocabulary_travel_information,
  ];

  static const List<String> _travelSentences = [
    LocaleKeys.sentences_travel_whereCanIBuyATicket,
    LocaleKeys.sentences_travel_whereDoesThisTrainGo,
    LocaleKeys.sentences_travel_whatTimeDoesTheBusLeave,
    LocaleKeys.sentences_travel_isThisTheCorrectPlatform,
    LocaleKeys.sentences_travel_doINeedToTransfer,
    LocaleKeys.sentences_travel_whichDirectionDoesThisMetroGo,
    LocaleKeys.sentences_travel_whatIsTheNextStop,
    LocaleKeys.sentences_travel_howCanIGetToTheAirport,
    LocaleKeys.sentences_travel_canYouCallATaxi,
    LocaleKeys.sentences_travel_isThisSeatFree,
    LocaleKeys.sentences_travel_isThereADelay,
    LocaleKeys.sentences_travel_myFlightWasCancelled,
    LocaleKeys.sentences_travel_iCantFindMyLuggage,
    LocaleKeys.sentences_travel_isThisTheRightWay,
    LocaleKeys.sentences_travel_canIGetSomeHelp,
  ];

  // ===========================================================================
  // 3. ACCOMMODATION
  // ===========================================================================
  static const List<String> _accommodationVocabulary = [
    LocaleKeys.vocabulary_accommodation_hotel,
    LocaleKeys.vocabulary_accommodation_hostel,
    LocaleKeys.vocabulary_accommodation_room,
    LocaleKeys.vocabulary_accommodation_reservation,
    LocaleKeys.vocabulary_accommodation_checkIn,
    LocaleKeys.vocabulary_accommodation_checkOut,
    LocaleKeys.vocabulary_accommodation_reception,
    LocaleKeys.vocabulary_accommodation_key,
    LocaleKeys.vocabulary_accommodation_card,
    LocaleKeys.vocabulary_accommodation_lobby,
    LocaleKeys.vocabulary_accommodation_floor,
    LocaleKeys.vocabulary_accommodation_elevator,
    LocaleKeys.vocabulary_accommodation_stairs,
    LocaleKeys.vocabulary_accommodation_bed,
    LocaleKeys.vocabulary_accommodation_pillow,
    LocaleKeys.vocabulary_accommodation_blanket,
    LocaleKeys.vocabulary_accommodation_towel,
    LocaleKeys.vocabulary_accommodation_bathroom,
    LocaleKeys.vocabulary_accommodation_shower,
    LocaleKeys.vocabulary_accommodation_toilet,
    LocaleKeys.vocabulary_accommodation_breakfast,
    LocaleKeys.vocabulary_accommodation_included,
    LocaleKeys.vocabulary_accommodation_fee,
    LocaleKeys.vocabulary_accommodation_payment,
    LocaleKeys.vocabulary_accommodation_invoice,
    LocaleKeys.vocabulary_accommodation_receipt,
    LocaleKeys.vocabulary_accommodation_cleaning,
    LocaleKeys.vocabulary_accommodation_dirty,
    LocaleKeys.vocabulary_accommodation_quiet,
    LocaleKeys.vocabulary_accommodation_noise,
    LocaleKeys.vocabulary_accommodation_view,
    LocaleKeys.vocabulary_accommodation_balcony,
    LocaleKeys.vocabulary_accommodation_airConditioning,
    LocaleKeys.vocabulary_accommodation_heating,
    LocaleKeys.vocabulary_accommodation_internet,
    LocaleKeys.vocabulary_accommodation_wiFi,
    LocaleKeys.vocabulary_accommodation_password,
    LocaleKeys.vocabulary_accommodation_roomService,
    LocaleKeys.vocabulary_accommodation_minibar,
    LocaleKeys.vocabulary_accommodation_safe,
    LocaleKeys.vocabulary_accommodation_malfunction,
    LocaleKeys.vocabulary_accommodation_change,
    LocaleKeys.vocabulary_accommodation_night,
    LocaleKeys.vocabulary_accommodation_stay,
    LocaleKeys.vocabulary_accommodation_vacantRoom,
    LocaleKeys.vocabulary_accommodation_occupiedRoom,
    LocaleKeys.vocabulary_accommodation_support,
    LocaleKeys.vocabulary_accommodation_staff,
  ];

  static const List<String> _accommodationSentences = [
    LocaleKeys.sentences_accommodation_iHaveAReservation,
    LocaleKeys.sentences_accommodation_canICheckIn,
    LocaleKeys.sentences_accommodation_whatTimeIsCheckOut,
    LocaleKeys.sentences_accommodation_isMyRoomReady,
    LocaleKeys.sentences_accommodation_canIGetMyRoomKey,
    LocaleKeys.sentences_accommodation_thereIsAProblemWithMyRoom,
    LocaleKeys.sentences_accommodation_theAirConditionerIsNotWorking,
    LocaleKeys.sentences_accommodation_isThereInternetAccess,
    LocaleKeys.sentences_accommodation_isBreakfastIncluded,
    LocaleKeys.sentences_accommodation_isThereRoomService,
    LocaleKeys.sentences_accommodation_canIGetATowel,
    LocaleKeys.sentences_accommodation_canIChangeRooms,
    LocaleKeys.sentences_accommodation_iWouldLikeToStayOneMoreNight,
    LocaleKeys.sentences_accommodation_canIGetTheBill,
    LocaleKeys.sentences_accommodation_canIGetSomeHelp,
  ];

  // ===========================================================================
  // 4. FOOD & DRINK
  // ===========================================================================
  static const List<String> _foodAndDrinkVocabulary = [
    LocaleKeys.vocabulary_foodAndDrink_menu,
    LocaleKeys.vocabulary_foodAndDrink_order,
    LocaleKeys.vocabulary_foodAndDrink_food,
    LocaleKeys.vocabulary_foodAndDrink_drink,
    LocaleKeys.vocabulary_foodAndDrink_water,
    LocaleKeys.vocabulary_foodAndDrink_tea,
    LocaleKeys.vocabulary_foodAndDrink_coffee,
    LocaleKeys.vocabulary_foodAndDrink_juice,
    LocaleKeys.vocabulary_foodAndDrink_soda,
    LocaleKeys.vocabulary_foodAndDrink_beer,
    LocaleKeys.vocabulary_foodAndDrink_wine,
    LocaleKeys.vocabulary_foodAndDrink_breakfast,
    LocaleKeys.vocabulary_foodAndDrink_lunch,
    LocaleKeys.vocabulary_foodAndDrink_dinner,
    LocaleKeys.vocabulary_foodAndDrink_snack,
    LocaleKeys.vocabulary_foodAndDrink_dessert,
    LocaleKeys.vocabulary_foodAndDrink_salty,
    LocaleKeys.vocabulary_foodAndDrink_spicy,
    LocaleKeys.vocabulary_foodAndDrink_hot,
    LocaleKeys.vocabulary_foodAndDrink_cold,
    LocaleKeys.vocabulary_foodAndDrink_fresh,
    LocaleKeys.vocabulary_foodAndDrink_delicious,
    LocaleKeys.vocabulary_foodAndDrink_vegetarian,
    LocaleKeys.vocabulary_foodAndDrink_vegan,
    LocaleKeys.vocabulary_foodAndDrink_meat,
    LocaleKeys.vocabulary_foodAndDrink_chicken,
    LocaleKeys.vocabulary_foodAndDrink_fish,
    LocaleKeys.vocabulary_foodAndDrink_rice,
    LocaleKeys.vocabulary_foodAndDrink_pasta,
    LocaleKeys.vocabulary_foodAndDrink_bread,
    LocaleKeys.vocabulary_foodAndDrink_soup,
    LocaleKeys.vocabulary_foodAndDrink_salad,
    LocaleKeys.vocabulary_foodAndDrink_cheese,
    LocaleKeys.vocabulary_foodAndDrink_sauce,
    LocaleKeys.vocabulary_foodAndDrink_oliveOil,
    LocaleKeys.vocabulary_foodAndDrink_sugar,
    LocaleKeys.vocabulary_foodAndDrink_salt,
    LocaleKeys.vocabulary_foodAndDrink_pepper,
    LocaleKeys.vocabulary_foodAndDrink_allergy,
    LocaleKeys.vocabulary_foodAndDrink_ingredients,
    LocaleKeys.vocabulary_foodAndDrink_portion,
    LocaleKeys.vocabulary_foodAndDrink_waiter,
    LocaleKeys.vocabulary_foodAndDrink_bill,
    LocaleKeys.vocabulary_foodAndDrink_check,
    LocaleKeys.vocabulary_foodAndDrink_tip,
    LocaleKeys.vocabulary_foodAndDrink_card,
    LocaleKeys.vocabulary_foodAndDrink_cash,
    LocaleKeys.vocabulary_foodAndDrink_takeaway,
    LocaleKeys.vocabulary_foodAndDrink_service,
    LocaleKeys.vocabulary_foodAndDrink_recommendation,
    LocaleKeys.vocabulary_foodAndDrink_reservation,
  ];

  static const List<String> _foodAndDrinkSentences = [
    LocaleKeys.sentences_foodAndDrink_canISeeTheMenu,
    LocaleKeys.sentences_foodAndDrink_iWouldLikeToOrder,
    LocaleKeys.sentences_foodAndDrink_iWantThis,
    LocaleKeys.sentences_foodAndDrink_canIGetSomethingElse,
    LocaleKeys.sentences_foodAndDrink_doYouHaveAnyRecommendations,
    LocaleKeys.sentences_foodAndDrink_isItSpicy,
    LocaleKeys.sentences_foodAndDrink_doYouHaveVegetarianFood,
    LocaleKeys.sentences_foodAndDrink_whatIsInIt,
    LocaleKeys.sentences_foodAndDrink_iHaveAnAllergy,
    LocaleKeys.sentences_foodAndDrink_canIGetSomeWater,
    LocaleKeys.sentences_foodAndDrink_canIGetTheBill,
    LocaleKeys.sentences_foodAndDrink_canIPayByCard,
    LocaleKeys.sentences_foodAndDrink_itWasVeryDelicious,
    LocaleKeys.sentences_foodAndDrink_canIGetThisToGo,
    LocaleKeys.sentences_foodAndDrink_thankYou,
  ];

  // ===========================================================================
  // 5. SIGHTSEEING
  // ===========================================================================
  static const List<String> _sightseeingVocabulary = [
    LocaleKeys.vocabulary_sightseeing_museum,
    LocaleKeys.vocabulary_sightseeing_park,
    LocaleKeys.vocabulary_sightseeing_beach,
    LocaleKeys.vocabulary_sightseeing_mountain,
    LocaleKeys.vocabulary_sightseeing_lake,
    LocaleKeys.vocabulary_sightseeing_river,
    LocaleKeys.vocabulary_sightseeing_forest,
    LocaleKeys.vocabulary_sightseeing_center,
    LocaleKeys.vocabulary_sightseeing_square,
    LocaleKeys.vocabulary_sightseeing_avenue,
    LocaleKeys.vocabulary_sightseeing_street,
    LocaleKeys.vocabulary_sightseeing_history,
    LocaleKeys.vocabulary_sightseeing_old,
    LocaleKeys.vocabulary_sightseeing_new,
    LocaleKeys.vocabulary_sightseeing_building,
    LocaleKeys.vocabulary_sightseeing_church,
    LocaleKeys.vocabulary_sightseeing_mosque,
    LocaleKeys.vocabulary_sightseeing_temple,
    LocaleKeys.vocabulary_sightseeing_castle,
    LocaleKeys.vocabulary_sightseeing_palace,
    LocaleKeys.vocabulary_sightseeing_monument,
    LocaleKeys.vocabulary_sightseeing_statue,
    LocaleKeys.vocabulary_sightseeing_gallery,
    LocaleKeys.vocabulary_sightseeing_exhibition,
    LocaleKeys.vocabulary_sightseeing_view,
    LocaleKeys.vocabulary_sightseeing_nature,
    LocaleKeys.vocabulary_sightseeing_photo,
    LocaleKeys.vocabulary_sightseeing_camera,
    LocaleKeys.vocabulary_sightseeing_ticket,
    LocaleKeys.vocabulary_sightseeing_entrance,
    LocaleKeys.vocabulary_sightseeing_exit,
    LocaleKeys.vocabulary_sightseeing_open,
    LocaleKeys.vocabulary_sightseeing_closed,
    LocaleKeys.vocabulary_sightseeing_time,
    LocaleKeys.vocabulary_sightseeing_guide,
    LocaleKeys.vocabulary_sightseeing_tour,
    LocaleKeys.vocabulary_sightseeing_map,
    LocaleKeys.vocabulary_sightseeing_walk,
    LocaleKeys.vocabulary_sightseeing_hiking,
    LocaleKeys.vocabulary_sightseeing_trail,
    LocaleKeys.vocabulary_sightseeing_near,
    LocaleKeys.vocabulary_sightseeing_far,
    LocaleKeys.vocabulary_sightseeing_famous,
    LocaleKeys.vocabulary_sightseeing_popular,
    LocaleKeys.vocabulary_sightseeing_beautiful,
    LocaleKeys.vocabulary_sightseeing_restroom,
    LocaleKeys.vocabulary_sightseeing_restArea,
    LocaleKeys.vocabulary_sightseeing_information,
    LocaleKeys.vocabulary_sightseeing_security,
    LocaleKeys.vocabulary_sightseeing_weather,
  ];

  static const List<String> _sightseeingSentences = [
    LocaleKeys.sentences_sightseeing_areTherePlacesToVisitHere,
    LocaleKeys.sentences_sightseeing_whatIsTheMostPopularPlace,
    LocaleKeys.sentences_sightseeing_howCanIGetThere,
    LocaleKeys.sentences_sightseeing_isThereAnEntranceFee,
    LocaleKeys.sentences_sightseeing_whatTimeDoesItOpen,
    LocaleKeys.sentences_sightseeing_whatTimeDoesItClose,
    LocaleKeys.sentences_sightseeing_isThereAGuide,
    LocaleKeys.sentences_sightseeing_canITakePhotos,
    LocaleKeys.sentences_sightseeing_isThereAMuseumNearby,
    LocaleKeys.sentences_sightseeing_isThereANaturePark,
    LocaleKeys.sentences_sightseeing_thisPlaceIsVeryBeautiful,
    LocaleKeys.sentences_sightseeing_canYouGoHikingHere,
    LocaleKeys.sentences_sightseeing_whereIsTheRestroom,
    LocaleKeys.sentences_sightseeing_isThereARestArea,
    LocaleKeys.sentences_sightseeing_canIGetSomeHelp,
  ];

  // ===========================================================================
  // 6. SHOPPING
  // ===========================================================================
  static const List<String> _shoppingVocabulary = [
    LocaleKeys.vocabulary_shopping_shop,
    LocaleKeys.vocabulary_shopping_store,
    LocaleKeys.vocabulary_shopping_market,
    LocaleKeys.vocabulary_shopping_mall,
    LocaleKeys.vocabulary_shopping_price,
    LocaleKeys.vocabulary_shopping_cheap,
    LocaleKeys.vocabulary_shopping_expensive,
    LocaleKeys.vocabulary_shopping_discount,
    LocaleKeys.vocabulary_shopping_promotion,
    LocaleKeys.vocabulary_shopping_buy,
    LocaleKeys.vocabulary_shopping_sell,
    LocaleKeys.vocabulary_shopping_cashier,
    LocaleKeys.vocabulary_shopping_receipt,
    LocaleKeys.vocabulary_shopping_returnItem,
    LocaleKeys.vocabulary_shopping_exchange,
    LocaleKeys.vocabulary_shopping_size,
    LocaleKeys.vocabulary_shopping_color,
    LocaleKeys.vocabulary_shopping_model,
    LocaleKeys.vocabulary_shopping_quality,
    LocaleKeys.vocabulary_shopping_brand,
    LocaleKeys.vocabulary_shopping_original,
    LocaleKeys.vocabulary_shopping_fake,
    LocaleKeys.vocabulary_shopping_new,
    LocaleKeys.vocabulary_shopping_used,
    LocaleKeys.vocabulary_shopping_tryOn,
    LocaleKeys.vocabulary_shopping_fit,
    LocaleKeys.vocabulary_shopping_clothes,
    LocaleKeys.vocabulary_shopping_shoes,
    LocaleKeys.vocabulary_shopping_bag,
    LocaleKeys.vocabulary_shopping_gift,
    LocaleKeys.vocabulary_shopping_souvenir,
    LocaleKeys.vocabulary_shopping_local,
    LocaleKeys.vocabulary_shopping_handmade,
    LocaleKeys.vocabulary_shopping_payment,
    LocaleKeys.vocabulary_shopping_cash,
    LocaleKeys.vocabulary_shopping_card,
    LocaleKeys.vocabulary_shopping_credit,
    LocaleKeys.vocabulary_shopping_total,
    LocaleKeys.vocabulary_shopping_amount,
    LocaleKeys.vocabulary_shopping_open,
    LocaleKeys.vocabulary_shopping_closed,
    LocaleKeys.vocabulary_shopping_box,
    LocaleKeys.vocabulary_shopping_warranty,
    LocaleKeys.vocabulary_shopping_stock,
    LocaleKeys.vocabulary_shopping_number,
    LocaleKeys.vocabulary_shopping_label,
    LocaleKeys.vocabulary_shopping_bargain,
    LocaleKeys.vocabulary_shopping_tax,
  ];

  static const List<String> _shoppingSentences = [
    LocaleKeys.sentences_shopping_howMuchIsThis,
    LocaleKeys.sentences_shopping_isThereACheaperOne,
    LocaleKeys.sentences_shopping_isThereADiscount,
    LocaleKeys.sentences_shopping_itsVeryExpensive,
    LocaleKeys.sentences_shopping_illTakeThis,
    LocaleKeys.sentences_shopping_doYouHaveAnotherColor,
    LocaleKeys.sentences_shopping_doYouHaveAnotherSize,
    LocaleKeys.sentences_shopping_canITryItOn,
    LocaleKeys.sentences_shopping_willThisFitMe,
    LocaleKeys.sentences_shopping_howIsTheQuality,
    LocaleKeys.sentences_shopping_canIPayByCard,
    LocaleKeys.sentences_shopping_canIGetAReceipt,
    LocaleKeys.sentences_shopping_canIReturnThis,
    LocaleKeys.sentences_shopping_iReallyLikeIt,
    LocaleKeys.sentences_shopping_thankYou,
  ];

  // ===========================================================================
  // 7. DIRECTIONS AND NAVIGATION
  // ===========================================================================
  static const List<String> _directionsVocabulary = [
    LocaleKeys.vocabulary_directionsAndNavigation_map,
    LocaleKeys.vocabulary_directionsAndNavigation_direction,
    LocaleKeys.vocabulary_directionsAndNavigation_right,
    LocaleKeys.vocabulary_directionsAndNavigation_left,
    LocaleKeys.vocabulary_directionsAndNavigation_straight,
    LocaleKeys.vocabulary_directionsAndNavigation_back,
    LocaleKeys.vocabulary_directionsAndNavigation_forward,
    LocaleKeys.vocabulary_directionsAndNavigation_near,
    LocaleKeys.vocabulary_directionsAndNavigation_far,
    LocaleKeys.vocabulary_directionsAndNavigation_distance,
    LocaleKeys.vocabulary_directionsAndNavigation_corner,
    LocaleKeys.vocabulary_directionsAndNavigation_street,
    LocaleKeys.vocabulary_directionsAndNavigation_avenue,
    LocaleKeys.vocabulary_directionsAndNavigation_road,
    LocaleKeys.vocabulary_directionsAndNavigation_intersection,
    LocaleKeys.vocabulary_directionsAndNavigation_bridge,
    LocaleKeys.vocabulary_directionsAndNavigation_crossing,
    LocaleKeys.vocabulary_directionsAndNavigation_trafficLight,
    LocaleKeys.vocabulary_directionsAndNavigation_sign,
    LocaleKeys.vocabulary_directionsAndNavigation_north,
    LocaleKeys.vocabulary_directionsAndNavigation_south,
    LocaleKeys.vocabulary_directionsAndNavigation_east,
    LocaleKeys.vocabulary_directionsAndNavigation_west,
    LocaleKeys.vocabulary_directionsAndNavigation_here,
    LocaleKeys.vocabulary_directionsAndNavigation_there,
    LocaleKeys.vocabulary_directionsAndNavigation_up,
    LocaleKeys.vocabulary_directionsAndNavigation_down,
    LocaleKeys.vocabulary_directionsAndNavigation_inside,
    LocaleKeys.vocabulary_directionsAndNavigation_outside,
    LocaleKeys.vocabulary_directionsAndNavigation_entrance,
    LocaleKeys.vocabulary_directionsAndNavigation_exit,
    LocaleKeys.vocabulary_directionsAndNavigation_turn,
    LocaleKeys.vocabulary_directionsAndNavigation_walk,
    LocaleKeys.vocabulary_directionsAndNavigation_drive,
    LocaleKeys.vocabulary_directionsAndNavigation_stop,
    LocaleKeys.vocabulary_directionsAndNavigation_station,
    LocaleKeys.vocabulary_directionsAndNavigation_location,
    LocaleKeys.vocabulary_directionsAndNavigation_address,
    LocaleKeys.vocabulary_directionsAndNavigation_getLost,
    LocaleKeys.vocabulary_directionsAndNavigation_find,
    LocaleKeys.vocabulary_directionsAndNavigation_follow,
    LocaleKeys.vocabulary_directionsAndNavigation_opposite,
    LocaleKeys.vocabulary_directionsAndNavigation_nextTo,
    LocaleKeys.vocabulary_directionsAndNavigation_between,
    LocaleKeys.vocabulary_directionsAndNavigation_next,
    LocaleKeys.vocabulary_directionsAndNavigation_previous,
    LocaleKeys.vocabulary_directionsAndNavigation_block,
    LocaleKeys.vocabulary_directionsAndNavigation_area,
    LocaleKeys.vocabulary_directionsAndNavigation_center,
    LocaleKeys.vocabulary_directionsAndNavigation_nearby,
    LocaleKeys.vocabulary_directionsAndNavigation_emergencyExit,
    LocaleKeys.vocabulary_directionsAndNavigation_wrongWay,
    LocaleKeys.vocabulary_directionsAndNavigation_rightWay,
  ];

  static const List<String> _directionsSentences = [
    LocaleKeys.sentences_directionsAndNavigation_imLost,
    LocaleKeys.sentences_directionsAndNavigation_howCanIGetHere,
    LocaleKeys.sentences_directionsAndNavigation_isThereANearby,
    LocaleKeys.sentences_directionsAndNavigation_howFarIsIt,
    LocaleKeys.sentences_directionsAndNavigation_canIWalkThere,
    LocaleKeys.sentences_directionsAndNavigation_canIGoByBus,
    LocaleKeys.sentences_directionsAndNavigation_toTheRightOrToTheLeft,
    LocaleKeys.sentences_directionsAndNavigation_shouldIGoStraight,
    LocaleKeys.sentences_directionsAndNavigation_isItFar,
    LocaleKeys.sentences_directionsAndNavigation_canYouShowMeOnTheMap,
    LocaleKeys.sentences_directionsAndNavigation_imHere,
    LocaleKeys.sentences_directionsAndNavigation_imLookingForTheAddress,
    LocaleKeys.sentences_directionsAndNavigation_imOnTheWrongWay,
    LocaleKeys.sentences_directionsAndNavigation_canYouHelpMe,
    LocaleKeys.sentences_directionsAndNavigation_thankYou,
  ];

  // ===========================================================================
  // 8. SPORTS
  // ===========================================================================
  static const List<String> _sportsVocabulary = [
    LocaleKeys.vocabulary_sports_gym,
    LocaleKeys.vocabulary_sports_fitness,
    LocaleKeys.vocabulary_sports_exercise,
    LocaleKeys.vocabulary_sports_workout,
    LocaleKeys.vocabulary_sports_trainer,
    LocaleKeys.vocabulary_sports_coach,
    LocaleKeys.vocabulary_sports_equipment,
    LocaleKeys.vocabulary_sports_machine,
    LocaleKeys.vocabulary_sports_weights,
    LocaleKeys.vocabulary_sports_cardio,
    LocaleKeys.vocabulary_sports_treadmill,
    LocaleKeys.vocabulary_sports_bike,
    LocaleKeys.vocabulary_sports_stretching,
    LocaleKeys.vocabulary_sports_warmUp,
    LocaleKeys.vocabulary_sports_coolDown,
    LocaleKeys.vocabulary_sports_class,
    LocaleKeys.vocabulary_sports_group,
    LocaleKeys.vocabulary_sports_yoga,
    LocaleKeys.vocabulary_sports_pilates,
    LocaleKeys.vocabulary_sports_boxing,
    LocaleKeys.vocabulary_sports_swimming,
    LocaleKeys.vocabulary_sports_pool,
    LocaleKeys.vocabulary_sports_lockerRoom,
    LocaleKeys.vocabulary_sports_shower,
    LocaleKeys.vocabulary_sports_towel,
    LocaleKeys.vocabulary_sports_membership,
    LocaleKeys.vocabulary_sports_registration,
    LocaleKeys.vocabulary_sports_dailyPass,
    LocaleKeys.vocabulary_sports_time,
    LocaleKeys.vocabulary_sports_schedule,
    LocaleKeys.vocabulary_sports_open,
    LocaleKeys.vocabulary_sports_closed,
    LocaleKeys.vocabulary_sports_fee,
    LocaleKeys.vocabulary_sports_price,
    LocaleKeys.vocabulary_sports_reservation,
    LocaleKeys.vocabulary_sports_participation,
    LocaleKeys.vocabulary_sports_start,
    LocaleKeys.vocabulary_sports_finish,
    LocaleKeys.vocabulary_sports_energy,
    LocaleKeys.vocabulary_sports_strength,
    LocaleKeys.vocabulary_sports_balance,
    LocaleKeys.vocabulary_sports_flexibility,
    LocaleKeys.vocabulary_sports_health,
    LocaleKeys.vocabulary_sports_active,
    LocaleKeys.vocabulary_sports_injury,
    LocaleKeys.vocabulary_sports_rest,
    LocaleKeys.vocabulary_sports_repeat,
  ];

  static const List<String> _sportsSentences = [
    LocaleKeys.sentences_sports_isThereAGym,
    LocaleKeys.sentences_sports_iWantToRegister,
    LocaleKeys.sentences_sports_isThereADailyPass,
    LocaleKeys.sentences_sports_whatTimeDoesItOpen,
    LocaleKeys.sentences_sports_howMuchDoesItCost,
    LocaleKeys.sentences_sports_isThereEquipment,
    LocaleKeys.sentences_sports_canIRentIt,
    LocaleKeys.sentences_sports_areThereGroupClasses,
    LocaleKeys.sentences_sports_isItOpenToday,
    LocaleKeys.sentences_sports_isThereAShower,
    LocaleKeys.sentences_sports_isThereATrainer,
    LocaleKeys.sentences_sports_isAReservationRequired,
    LocaleKeys.sentences_sports_canIJoin,
    LocaleKeys.sentences_sports_itWasVeryEnjoyable,
    LocaleKeys.sentences_sports_thankYou,
  ];

  // ===========================================================================
  // 9. HEALTH
  // ===========================================================================
  static const List<String> _healthVocabulary = [
    LocaleKeys.vocabulary_health_doctor,
    LocaleKeys.vocabulary_health_nurse,
    LocaleKeys.vocabulary_health_hospital,
    LocaleKeys.vocabulary_health_clinic,
    LocaleKeys.vocabulary_health_pharmacy,
    LocaleKeys.vocabulary_health_medicine,
    LocaleKeys.vocabulary_health_pain,
    LocaleKeys.vocabulary_health_ache,
    LocaleKeys.vocabulary_health_headache,
    LocaleKeys.vocabulary_health_stomachache,
    LocaleKeys.vocabulary_health_fever,
    LocaleKeys.vocabulary_health_cold,
    LocaleKeys.vocabulary_health_flu,
    LocaleKeys.vocabulary_health_allergy,
    LocaleKeys.vocabulary_health_injury,
    LocaleKeys.vocabulary_health_wound,
    LocaleKeys.vocabulary_health_blood,
    LocaleKeys.vocabulary_health_bloodPressure,
    LocaleKeys.vocabulary_health_emergency,
    LocaleKeys.vocabulary_health_er,
    LocaleKeys.vocabulary_health_ambulance,
    LocaleKeys.vocabulary_health_treatment,
    LocaleKeys.vocabulary_health_appointment,
    LocaleKeys.vocabulary_health_checkUp,
    LocaleKeys.vocabulary_health_symptom,
    LocaleKeys.vocabulary_health_sick,
    LocaleKeys.vocabulary_health_healthy,
    LocaleKeys.vocabulary_health_insurance,
    LocaleKeys.vocabulary_health_mask,
    LocaleKeys.vocabulary_health_bandage,
    LocaleKeys.vocabulary_health_prescription,
    LocaleKeys.vocabulary_health_dose,
    LocaleKeys.vocabulary_health_daily,
    LocaleKeys.vocabulary_health_night,
    LocaleKeys.vocabulary_health_morning,
    LocaleKeys.vocabulary_health_rest,
    LocaleKeys.vocabulary_health_sleep,
    LocaleKeys.vocabulary_health_water,
    LocaleKeys.vocabulary_health_nausea,
    LocaleKeys.vocabulary_health_vomiting,
    LocaleKeys.vocabulary_health_dizziness,
    LocaleKeys.vocabulary_health_weakness,
    LocaleKeys.vocabulary_health_swelling,
    LocaleKeys.vocabulary_health_itching,
    LocaleKeys.vocabulary_health_breath,
    LocaleKeys.vocabulary_health_fracture,
    LocaleKeys.vocabulary_health_burn,
    LocaleKeys.vocabulary_health_infection,
    LocaleKeys.vocabulary_health_vaccine,
  ];

  static const List<String> _healthSentences = [
    LocaleKeys.sentences_health_iDontFeelWell,
    LocaleKeys.sentences_health_iNeedADoctor,
    LocaleKeys.sentences_health_imInPain,
    LocaleKeys.sentences_health_iHaveAHeadache,
    LocaleKeys.sentences_health_myStomachHurts,
    LocaleKeys.sentences_health_iHaveAFever,
    LocaleKeys.sentences_health_whereIsThePharmacy,
    LocaleKeys.sentences_health_canIGetMedicine,
    LocaleKeys.sentences_health_iHaveAnAllergy,
    LocaleKeys.sentences_health_itsAnEmergency,
    LocaleKeys.sentences_health_canYouCallAnAmbulance,
    LocaleKeys.sentences_health_iNeedToGoToTheHospital,
    LocaleKeys.sentences_health_itHurtsHere,
    LocaleKeys.sentences_health_canYouHelpMe,
    LocaleKeys.sentences_health_thankYou,
  ];

  // ===========================================================================
  // 10. BUSINESS
  // ===========================================================================
  static const List<String> _businessVocabulary = [
    LocaleKeys.vocabulary_business_meeting,
    LocaleKeys.vocabulary_business_company,
    LocaleKeys.vocabulary_business_office,
    LocaleKeys.vocabulary_business_work,
    LocaleKeys.vocabulary_business_project,
    LocaleKeys.vocabulary_business_client,
    LocaleKeys.vocabulary_business_partner,
    LocaleKeys.vocabulary_business_manager,
    LocaleKeys.vocabulary_business_team,
    LocaleKeys.vocabulary_business_calendar,
    LocaleKeys.vocabulary_business_agenda,
    LocaleKeys.vocabulary_business_presentation,
    LocaleKeys.vocabulary_business_report,
    LocaleKeys.vocabulary_business_contract,
    LocaleKeys.vocabulary_business_agreement,
    LocaleKeys.vocabulary_business_offer,
    LocaleKeys.vocabulary_business_price,
    LocaleKeys.vocabulary_business_budget,
    LocaleKeys.vocabulary_business_payment,
    LocaleKeys.vocabulary_business_invoice,
    LocaleKeys.vocabulary_business_email,
    LocaleKeys.vocabulary_business_phone,
    LocaleKeys.vocabulary_business_call,
    LocaleKeys.vocabulary_business_number,
    LocaleKeys.vocabulary_business_address,
    LocaleKeys.vocabulary_business_deadline,
    LocaleKeys.vocabulary_business_plan,
    LocaleKeys.vocabulary_business_strategy,
    LocaleKeys.vocabulary_business_market,
    LocaleKeys.vocabulary_business_sales,
    LocaleKeys.vocabulary_business_growth,
    LocaleKeys.vocabulary_business_target,
    LocaleKeys.vocabulary_business_goal,
    LocaleKeys.vocabulary_business_result,
    LocaleKeys.vocabulary_business_progress,
    LocaleKeys.vocabulary_business_success,
    LocaleKeys.vocabulary_business_problem,
    LocaleKeys.vocabulary_business_solution,
    LocaleKeys.vocabulary_business_feedback,
    LocaleKeys.vocabulary_business_discussion,
    LocaleKeys.vocabulary_business_decision,
    LocaleKeys.vocabulary_business_approval,
    LocaleKeys.vocabulary_business_signature,
    LocaleKeys.vocabulary_business_document,
    LocaleKeys.vocabulary_business_file,
    LocaleKeys.vocabulary_business_attachment,
    LocaleKeys.vocabulary_business_appointment,
    LocaleKeys.vocabulary_business_availability,
    LocaleKeys.vocabulary_business_connection,
    LocaleKeys.vocabulary_business_communication,
  ];

  static const List<String> _businessSentences = [
    LocaleKeys.sentences_business_niceToMeetYou,
    LocaleKeys.sentences_business_imFromCompany,
    LocaleKeys.sentences_business_weHaveAMeeting,
    LocaleKeys.sentences_business_whatTimeDoesItStart,
    LocaleKeys.sentences_business_whereIsTheMeeting,
    LocaleKeys.sentences_business_iWillBeLate,
    LocaleKeys.sentences_business_areYouAvailable,
    LocaleKeys.sentences_business_iWillSendAnEmail,
    LocaleKeys.sentences_business_letsMeetAgain,
    LocaleKeys.sentences_business_letsStayInTouch,
    LocaleKeys.sentences_business_canIGetYourBusinessCard,
    LocaleKeys.sentences_business_iWillGiveAPresentation,
    LocaleKeys.sentences_business_weHaveAnAgreement,
    LocaleKeys.sentences_business_thankYou,
    LocaleKeys.sentences_business_haveAGoodWorkday,
  ];

  // ===========================================================================
  // 11. EMERGENCY
  // ===========================================================================
  static const List<String> _emergencyVocabulary = [
    LocaleKeys.vocabulary_emergency_help,
    LocaleKeys.vocabulary_emergency_emergency,
    LocaleKeys.vocabulary_emergency_danger,
    LocaleKeys.vocabulary_emergency_police,
    LocaleKeys.vocabulary_emergency_ambulance,
    LocaleKeys.vocabulary_emergency_fireDepartment,
    LocaleKeys.vocabulary_emergency_fire,
    LocaleKeys.vocabulary_emergency_accident,
    LocaleKeys.vocabulary_emergency_injured,
    LocaleKeys.vocabulary_emergency_theft,
    LocaleKeys.vocabulary_emergency_stolen,
    LocaleKeys.vocabulary_emergency_lost,
    LocaleKeys.vocabulary_emergency_wallet,
    LocaleKeys.vocabulary_emergency_phone,
    LocaleKeys.vocabulary_emergency_passport,
    LocaleKeys.vocabulary_emergency_bag,
    LocaleKeys.vocabulary_emergency_safe,
    LocaleKeys.vocabulary_emergency_unsafe,
    LocaleKeys.vocabulary_emergency_fear,
    LocaleKeys.vocabulary_emergency_panic,
    LocaleKeys.vocabulary_emergency_immediately,
    LocaleKeys.vocabulary_emergency_now,
    LocaleKeys.vocabulary_emergency_call,
    LocaleKeys.vocabulary_emergency_number,
    LocaleKeys.vocabulary_emergency_location,
    LocaleKeys.vocabulary_emergency_here,
    LocaleKeys.vocabulary_emergency_wait,
    LocaleKeys.vocabulary_emergency_run,
    LocaleKeys.vocabulary_emergency_stop,
    LocaleKeys.vocabulary_emergency_follow,
    LocaleKeys.vocabulary_emergency_stay,
    LocaleKeys.vocabulary_emergency_go,
    LocaleKeys.vocabulary_emergency_exit,
    LocaleKeys.vocabulary_emergency_entrance,
    LocaleKeys.vocabulary_emergency_crowd,
    LocaleKeys.vocabulary_emergency_noise,
    LocaleKeys.vocabulary_emergency_scream,
    LocaleKeys.vocabulary_emergency_protect,
    LocaleKeys.vocabulary_emergency_security,
    LocaleKeys.vocabulary_emergency_alarm,
    LocaleKeys.vocabulary_emergency_report,
    LocaleKeys.vocabulary_emergency_complaint,
    LocaleKeys.vocabulary_emergency_support,
    LocaleKeys.vocabulary_emergency_shelter,
    LocaleKeys.vocabulary_emergency_lighting,
    LocaleKeys.vocabulary_emergency_lock,
    LocaleKeys.vocabulary_emergency_camera,
    LocaleKeys.vocabulary_emergency_injury,
    LocaleKeys.vocabulary_emergency_threat,
    LocaleKeys.vocabulary_emergency_witness,
  ];

  static const List<String> _emergencySentences = [
    LocaleKeys.sentences_emergency_help,
    LocaleKeys.sentences_emergency_iNeedUrgentHelp,
    LocaleKeys.sentences_emergency_callThePolice,
    LocaleKeys.sentences_emergency_callAnAmbulance,
    LocaleKeys.sentences_emergency_iLostMyWallet,
    LocaleKeys.sentences_emergency_iLostMyPhone,
    LocaleKeys.sentences_emergency_iLostMyPassport,
    LocaleKeys.sentences_emergency_thereWasATheft,
    LocaleKeys.sentences_emergency_imNotSafe,
    LocaleKeys.sentences_emergency_stayHere,
    LocaleKeys.sentences_emergency_followMe,
    LocaleKeys.sentences_emergency_iNeedHelp,
    LocaleKeys.sentences_emergency_whatShouldIDo,
    LocaleKeys.sentences_emergency_imVeryScared,
    LocaleKeys.sentences_emergency_pleaseHelpMe,
  ];
}
